baseurl: /jekylll
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
email: your-email@example.com
github_username: jekyll
plugins:
- jekyll-feed
theme: minima
title: Your awesome title
twitter_username: jekyllrb
url: https://thuhoai27.github.io
